import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router'
import {
  AnswerGrid,
  ExerciseHeader,
  ModalSheet,
  ReplayButton,
  SilentSwitchHint,
} from '../components'
import { IntervalMenu } from '../customize'
import { piano, scheduleDurationMs } from '../audio'
import {
  intervalScoreStore,
  intervalSettingsStore,
  intervalStatsStore,
  itemId,
  recordInStore,
  recordGuess,
  usePersisted,
} from '../settings'
import {
  buildCells,
  canGenerate,
  generateIntervalQuestion,
  groupsForAnswerPreview,
  groupsForQuestion,
  isCorrect,
  type IntervalQuestion,
} from '../exercises'

/** Minimum pause on the green button before the next question starts. */
const AUTO_ADVANCE_MS = 800

/** Silence left after a confirming interval finishes, before the next question. */
const ADVANCE_GAP_MS = 250

interface Round {
  number: number
  question: IntervalQuestion
}

export default function Intervals() {
  const navigate = useNavigate()
  const [settings] = usePersisted(intervalSettingsStore)
  const [score, setScore, resetScore] = usePersisted(intervalScoreStore)

  /**
   * Whether this question has already gone into the statistics.
   *
   * The *score* counts every press — three misses then a hit is 1/4, and that
   * is the right thing for a scoreboard. Statistics want a different fact:
   * whether the user knew it, which only the first press can answer. Later
   * presses on the same question are process of elimination, and counting them
   * would make every interval look easier the longer someone struggled with it.
   *
   * A ref rather than deriving it from `wrong` and `solved`, for the reason
   * the melody and progression screens keep one: two presses inside a single
   * React batch both read the state their render was built with.
   */
  const measured = useRef(false)

  // Each question is wrapped with a round number so that "a new question
  // arrived" never depends on object identity — two consecutive questions can
  // legitimately be structurally identical.
  const [round, setRound] = useState<Round | null>(null)
  const [wrong, setWrong] = useState<number[]>([])
  const [solved, setSolved] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const advanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const replayRef = useRef<HTMLButtonElement>(null)

  const playable = canGenerate(settings)

  const nextQuestion = useCallback(() => {
    setWrong([])
    setSolved(false)
    measured.current = false
    setRound((current) => ({
      number: (current?.number ?? 0) + 1,
      question: generateIntervalQuestion(
        settings,
        undefined,
        intervalStatsStore.read(),
      ),
    }))
  }, [settings])

  // Play whenever a new question arrives. The first question is generated by
  // the start button, which is also what unlocks audio (see below).
  useEffect(() => {
    if (!round) return
    void piano.play(groupsForQuestion(round.question))
  }, [round])

  // Changing settings invalidates the current question.
  useEffect(() => {
    setRound(null)
    setWrong([])
    setSolved(false)
    measured.current = false
  }, [settings])

  // Park focus on Replay for every new question, so a keyboard user can
  // press space to hear it again rather than activating whichever answer
  // button they last pressed.
  useEffect(() => {
    if (!round) return
    replayRef.current?.focus()
  }, [round])

  useEffect(
    () => () => {
      if (advanceTimer.current) clearTimeout(advanceTimer.current)
      piano.stop()
    },
    [],
  )

  const handleAnswer = (semitones: number) => {
    if (!round) return

    // Always sound the interval that was pressed, from the question's own
    // reference note. A wrong guess then becomes a direct comparison against
    // the target rather than just a red button.
    const groups = groupsForAnswerPreview(round.question, semitones)
    if (groups) void piano.play(groups)

    // Pressing an answer that has already been given — or any answer once the
    // question is solved — replays its sound without scoring again.
    if (solved || wrong.includes(semitones)) return

    const correct = isCorrect(round.question, semitones)
    setScore(recordGuess(score, correct))

    if (!measured.current) {
      measured.current = true
      recordInStore(intervalStatsStore, [
        {
          item: itemId('interval', round.question.answer),
          correct,
          answered: String(semitones),
        },
        // The same interval descending is a different skill from ascending,
        // and harmonic is a third. Recorded separately so the breakdown can
        // say which.
        { item: itemId('mode', round.question.playMode), correct },
      ])
    }

    if (!correct) {
      setWrong((current) => [...current, semitones])
      return
    }

    setSolved(true)
    // Let the confirming interval finish before the next question interrupts.
    const settle = groups
      ? Math.max(AUTO_ADVANCE_MS, scheduleDurationMs(groups) + ADVANCE_GAP_MS)
      : AUTO_ADVANCE_MS
    advanceTimer.current = setTimeout(nextQuestion, settle)
  }

  return (
    <main className="flex h-full flex-col">
      <ExerciseHeader
        correct={score.correct}
        total={score.total}
        onBack={() => navigate('/')}
        onMenu={() => setMenuOpen(true)}
      />

      {round ? (
        <>
          <div className="flex justify-center py-1">
            <ReplayButton
              ref={replayRef}
              onClick={() => void piano.play(groupsForQuestion(round.question))}
            />
          </div>
          <SilentSwitchHint />
          <AnswerGrid
            cells={buildCells(
              settings.intervals,
              wrong,
              solved,
              round.question,
            )}
            // Grid ids are strings; intervals are keyed by semitone count.
            onAnswer={(id) => handleAnswer(Number(id))}
          />
        </>
      ) : (
        <StartPanel playable={playable} onStart={nextQuestion} />
      )}

      <ModalSheet
        open={menuOpen}
        onClose={() => setMenuOpen(false)}
        title="Menu"
      >
        <IntervalMenu
          onResetScore={() => {
            resetScore()
            setMenuOpen(false)
          }}
        />
      </ModalSheet>
    </main>
  )
}

function StartPanel({
  playable,
  onStart,
}: {
  playable: boolean
  onStart: () => void
}) {
  if (!playable) {
    return (
      <div className="flex flex-1 items-center justify-center p-8 text-center text-content-muted">
        No interval can be played with the current settings. Open the menu and
        widen the range or enable more intervals.
      </div>
    )
  }

  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-4 p-8">
      {/*
        The first note has to be triggered by a real tap. iOS Safari starts the
        AudioContext suspended and will not resume it from an effect, so
        auto-playing on mount would be silent (see #22).
      */}
      <button
        type="button"
        onClick={onStart}
        className="rounded-full bg-accent px-8 py-3 text-lg font-medium active:opacity-80"
      >
        Start
      </button>
      <p className="text-center text-sm text-content-muted">
        Listen, then pick the interval you heard.
      </p>
    </div>
  )
}
