import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router'
import { AnswerGrid, ExerciseHeader, ModalSheet } from '../components'
import { IntervalMenu } from '../customize'
import { piano } from '../audio'
import {
  intervalScoreStore,
  intervalSettingsStore,
  recordGuess,
  usePersisted,
} from '../settings'
import {
  buildCells,
  canGenerate,
  generateIntervalQuestion,
  groupsForQuestion,
  isCorrect,
  type IntervalQuestion,
} from '../exercises'

/** Pause on the green button before the next question starts. */
const AUTO_ADVANCE_MS = 800

interface Round {
  number: number
  question: IntervalQuestion
}

export default function Intervals() {
  const navigate = useNavigate()
  const [settings] = usePersisted(intervalSettingsStore)
  const [score, setScore, resetScore] = usePersisted(intervalScoreStore)

  // Each question is wrapped with a round number so that "a new question
  // arrived" never depends on object identity — two consecutive questions can
  // legitimately be structurally identical.
  const [round, setRound] = useState<Round | null>(null)
  const [wrong, setWrong] = useState<number[]>([])
  const [solved, setSolved] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const advanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const playable = canGenerate(settings)

  const nextQuestion = useCallback(() => {
    setWrong([])
    setSolved(false)
    setRound((current) => ({
      number: (current?.number ?? 0) + 1,
      question: generateIntervalQuestion(settings),
    }))
  }, [settings])

  // Play whenever a new question arrives. The first question is generated by
  // the start button, which is also what unlocks audio (see below).
  useEffect(() => {
    if (!round) return
    void piano.play(groupsForQuestion(round.question))
  }, [round])

  // Changing settings invalidates the current question.
  useEffect(() => {
    setRound(null)
    setWrong([])
    setSolved(false)
  }, [settings])

  useEffect(
    () => () => {
      if (advanceTimer.current) clearTimeout(advanceTimer.current)
      piano.stop()
    },
    [],
  )

  const handleAnswer = (semitones: number) => {
    if (!round || solved) return

    const correct = isCorrect(round.question, semitones)
    setScore(recordGuess(score, correct))

    if (!correct) {
      setWrong((current) => [...current, semitones])
      return
    }

    setSolved(true)
    advanceTimer.current = setTimeout(nextQuestion, AUTO_ADVANCE_MS)
  }

  return (
    <main className="flex h-full flex-col">
      <ExerciseHeader
        correct={score.correct}
        total={score.total}
        onBack={() => navigate('/')}
        onMenu={() => setMenuOpen(true)}
      />

      {round ? (
        <>
          <div className="flex justify-center py-1">
            <ReplayButton
              onClick={() => void piano.play(groupsForQuestion(round.question))}
            />
          </div>
          <AnswerGrid
            cells={buildCells(
              settings.intervals,
              wrong,
              solved,
              round.question,
            )}
            // Grid ids are strings; intervals are keyed by semitone count.
            onAnswer={(id) => handleAnswer(Number(id))}
          />
        </>
      ) : (
        <StartPanel playable={playable} onStart={nextQuestion} />
      )}

      <ModalSheet
        open={menuOpen}
        onClose={() => setMenuOpen(false)}
        title="Menu"
      >
        <IntervalMenu
          onResetScore={() => {
            resetScore()
            setMenuOpen(false)
          }}
        />
      </ModalSheet>
    </main>
  )
}

function StartPanel({
  playable,
  onStart,
}: {
  playable: boolean
  onStart: () => void
}) {
  if (!playable) {
    return (
      <div className="flex flex-1 items-center justify-center p-8 text-center text-content-muted">
        No interval can be played with the current settings. Open the menu and
        widen the range or enable more intervals.
      </div>
    )
  }

  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-4 p-8">
      {/*
        The first note has to be triggered by a real tap. iOS Safari starts the
        AudioContext suspended and will not resume it from an effect, so
        auto-playing on mount would be silent (see #22).
      */}
      <button
        type="button"
        onClick={onStart}
        className="rounded-full bg-accent px-8 py-3 text-lg font-medium active:opacity-80"
      >
        Start
      </button>
      <p className="text-center text-sm text-content-muted">
        Listen, then pick the interval you heard.
      </p>
    </div>
  )
}

function ReplayButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-label="Play again"
      className="flex h-11 w-11 items-center justify-center rounded-full bg-surface active:bg-surface-raised"
    >
      <svg
        aria-hidden
        viewBox="0 0 24 24"
        className="h-6 w-6"
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M4 9v6h4l5 4V5L8 9H4z" fill="currentColor" stroke="none" />
        <path d="M16.5 8.5a5 5 0 010 7" />
        <path d="M19 6a8.5 8.5 0 010 12" />
      </svg>
    </button>
  )
}
